/* Generated by gliss-csim ($(date)) copyright (c) 2024 IRIT - UPS */

#ifndef  $(ARCH)_$(COMP)_H
#define  $(ARCH)_$(COMP)_H

#include <csim.h>

extern csim_component_t  $(comp)_component;

#endif /*  $(ARCH)_$(COMP)_H */
