/* Generated by gliss-csim (125/03/26 13:55:55) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_OSCILLATOR_H
#define  ATMEGA328P_OSCILLATOR_H

#include <csim.h>

extern csim_component_t  oscillator_component;

#endif /*  ATMEGA328P_OSCILLATOR_H */
