/* Generated by gliss-csim (125/03/22 17:10:45) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_PORTD_H
#define  ATMEGA328P_PORTD_H

#include <csim.h>

extern csim_component_t  portd_component;

#endif /*  ATMEGA328P_PORTD_H */
