/* Generated by gliss-csim (125/03/24 10:46:17) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_PORTC_H
#define  ATMEGA328P_PORTC_H

#include <csim.h>

extern csim_component_t  portc_component;

#endif /*  ATMEGA328P_PORTC_H */
