/* Generated by gliss-csim (125/03/23 11:07:47) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_PORTB_H
#define  ATMEGA328P_PORTB_H

#include <csim.h>

extern csim_component_t  portb_component;

#endif /*  ATMEGA328P_PORTB_H */
