/* Generated by gliss-csim (124/03/03 17:43:32) copyright (c) 2024 IRIT - UPS */

#include <stdio.h>
#include <stdlib.h>
#include <csim.h>
#include "csim-rt.h"


#define ____COMP_NUM		(inst->number)
#	define _HEX03	__inst->HEX03
#	define _HEX45	__inst->HEX45

#	define HEX5_BASE	0
#	define _HEX5	__inst->HEX5
#	define HEX5_PORT	&ports[HEX5_BASE]
#		define HEX5_SET(i, x)	\
			{ \
				if(_HEX5[i] != x) { \
					_HEX5[i] = x; \
					csim_send_digital(inst, HEX5_PORT + i, _HEX5[i]); \
				} \
			}
#	define HEX2_BASE	8
#	define _HEX2	__inst->HEX2
#	define HEX2_PORT	&ports[HEX2_BASE]
#		define HEX2_SET(i, x)	\
			{ \
				if(_HEX2[i] != x) { \
					_HEX2[i] = x; \
					csim_send_digital(inst, HEX2_PORT + i, _HEX2[i]); \
				} \
			}
#	define HEX1_BASE	16
#	define _HEX1	__inst->HEX1
#	define HEX1_PORT	&ports[HEX1_BASE]
#		define HEX1_SET(i, x)	\
			{ \
				if(_HEX1[i] != x) { \
					_HEX1[i] = x; \
					csim_send_digital(inst, HEX1_PORT + i, _HEX1[i]); \
				} \
			}
#	define HEX4_BASE	24
#	define _HEX4	__inst->HEX4
#	define HEX4_PORT	&ports[HEX4_BASE]
#		define HEX4_SET(i, x)	\
			{ \
				if(_HEX4[i] != x) { \
					_HEX4[i] = x; \
					csim_send_digital(inst, HEX4_PORT + i, _HEX4[i]); \
				} \
			}
#	define HEX3_BASE	32
#	define _HEX3	__inst->HEX3
#	define HEX3_PORT	&ports[HEX3_BASE]
#		define HEX3_SET(i, x)	\
			{ \
				if(_HEX3[i] != x) { \
					_HEX3[i] = x; \
					csim_send_digital(inst, HEX3_PORT + i, _HEX3[i]); \
				} \
			}
#	define HEX0_BASE	40
#	define _HEX0	__inst->HEX0
#	define HEX0_PORT	&ports[HEX0_BASE]
#		define HEX0_SET(i, x)	\
			{ \
				if(_HEX0[i] != x) { \
					_HEX0[i] = x; \
					csim_send_digital(inst, HEX0_PORT + i, _HEX0[i]); \
				} \
			}


/**
 * Instance definition.
 */
typedef struct  seven_seg_controller_inst_t {
    csim_inst_t inst;
			uint32_t HEX03;
			uint32_t HEX45;

			uint8_t HEX5[8];
			uint8_t HEX2[8];
			uint8_t HEX1[8];
			uint8_t HEX4[8];
			uint8_t HEX3[8];
			uint8_t HEX0[8];
;
}  seven_seg_controller_inst_t;


/* pre-definitiion of update functions */
	static void on_update_HEX5(csim_inst_t *inst);
	static void on_update_HEX2(csim_inst_t *inst);
	static void on_update_HEX1(csim_inst_t *inst);
	static void on_update_HEX4(csim_inst_t *inst);
	static void on_update_HEX3(csim_inst_t *inst);
	static void on_update_HEX0(csim_inst_t *inst);


static void on_update_all(csim_inst_t *inst) {
		on_update_HEX5(inst);
		on_update_HEX2(inst);
		on_update_HEX1(inst);
		on_update_HEX4(inst);
		on_update_HEX3(inst);
		on_update_HEX0(inst);
	
}


/**
 * Reset the instance.
 * @param inst	Instance to reset.
 */
static void  seven_seg_controller_reset(csim_inst_t *inst) {
    seven_seg_controller_inst_t * seven_seg_controller_inst = ( seven_seg_controller_inst_t *)inst;
}

/**
 * Construct an instance.
 * @param inst	Instance to construct.
 */
static void seven_seg_controller_construct(csim_inst_t *inst, csim_confs_t confs) {
    seven_seg_controller_inst_t * seven_seg_controller_inst = ( seven_seg_controller_inst_t *)inst;
    seven_seg_controller_reset(inst);
}

/**
 * Destruct the instance.
 * @param inst	Instance to destruct.
 */
static void seven_seg_controller_destruct(csim_inst_t *inst) {
}


/* HEX03 register functions */

static void name_HEX03(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	snprintf(__buffer, size, "seven_seg_controller%d_HEX03", inst->number);
}

static void display_HEX03(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->HEX03);;
}

static csim_word_t read_HEX03(csim_inst_t *inst, int num) {
		seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
				return __inst->HEX03;
}
 
static csim_word_t get_HEX03(csim_inst_t *inst, int num) {
		seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
			return __inst->HEX03;
}
 
static void set_HEX03(csim_inst_t *inst, int num, csim_word_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
		if(__inst->HEX03 != val) {
			__inst->HEX03 = val;
			on_update_all(inst);
		}
	
}

static void write_HEX03(csim_inst_t *inst, int num, csim_word_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
		set_HEX03(inst, num, val);
	
}

/* HEX45 register functions */

static void name_HEX45(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	snprintf(__buffer, size, "seven_seg_controller%d_HEX45", inst->number);
}

static void display_HEX45(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->HEX45);;
}

static csim_word_t read_HEX45(csim_inst_t *inst, int num) {
		seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
				return __inst->HEX45;
}
 
static csim_word_t get_HEX45(csim_inst_t *inst, int num) {
		seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
			return __inst->HEX45;
}
 
static void set_HEX45(csim_inst_t *inst, int num, csim_word_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
		if(__inst->HEX45 != val) {
			__inst->HEX45 = val;
			on_update_all(inst);
		}
	
}

static void write_HEX45(csim_inst_t *inst, int num, csim_word_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
		set_HEX45(inst, num, val);
	
}




/**
 * Array of registers.
 */
static csim_reg_t regs[] = {
	{
		"HEX03",		// name
		0x0,		// offset
		32,		// size
		1,		// count
		4,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_HEX03,
		display_HEX03,
		read_HEX03,
		write_HEX03,
		get_HEX03,
		set_HEX03
	},
	{
		"HEX45",		// name
		0x10,		// offset
		32,		// size
		1,		// count
		4,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_HEX45,
		display_HEX45,
		read_HEX45,
		write_HEX45,
		get_HEX45,
		set_HEX45
	},

};


/* predeclaration of port-functions */
static void on_input_HEX5(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX2(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX1(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX4(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX3(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX0(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);



/**
 * Array of ports.
 */
static csim_port_t ports[] = {
				{
					"HEX50",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX51",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX52",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX53",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX54",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX55",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX56",
					CSIM_ELECTRIC,
					on_input_HEX5
				},
				{
					"HEX57",
					CSIM_ELECTRIC,
					on_input_HEX5
				},

				{
					"HEX20",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX21",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX22",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX23",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX24",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX25",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX26",
					CSIM_ELECTRIC,
					on_input_HEX2
				},
				{
					"HEX27",
					CSIM_ELECTRIC,
					on_input_HEX2
				},

				{
					"HEX10",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX11",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX12",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX13",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX14",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX15",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX16",
					CSIM_ELECTRIC,
					on_input_HEX1
				},
				{
					"HEX17",
					CSIM_ELECTRIC,
					on_input_HEX1
				},

				{
					"HEX40",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX41",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX42",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX43",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX44",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX45",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX46",
					CSIM_ELECTRIC,
					on_input_HEX4
				},
				{
					"HEX47",
					CSIM_ELECTRIC,
					on_input_HEX4
				},

				{
					"HEX30",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX31",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX32",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX33",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX34",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX35",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX36",
					CSIM_ELECTRIC,
					on_input_HEX3
				},
				{
					"HEX37",
					CSIM_ELECTRIC,
					on_input_HEX3
				},

				{
					"HEX00",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX01",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX02",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX03",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX04",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX05",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX06",
					CSIM_ELECTRIC,
					on_input_HEX0
				},
				{
					"HEX07",
					CSIM_ELECTRIC,
					on_input_HEX0
				},


};


/* HEX5 port functions */

static void on_input_HEX5(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX5_BASE);

}

static void on_update_HEX5(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_5_i;
	for(__gliss_5_i = 8; __gliss_5_i != 15+ 1; __gliss_5_i++)
		HEX5_SET((__gliss_5_i % 8), ((uint8_t)(_field32_generic(_HEX45, __gliss_5_i, __gliss_5_i, 1 ))));

}

/* HEX2 port functions */

static void on_input_HEX2(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX2_BASE);

}

static void on_update_HEX2(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_2_i;
	for(__gliss_2_i = 16; __gliss_2_i != 23+ 1; __gliss_2_i++)
		HEX2_SET((__gliss_2_i % 8), ((uint8_t)(_field32_generic(_HEX03, __gliss_2_i, __gliss_2_i, 1 ))));

}

/* HEX1 port functions */

static void on_input_HEX1(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX1_BASE);

}

static void on_update_HEX1(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_1_i;
	for(__gliss_1_i = 8; __gliss_1_i != 15+ 1; __gliss_1_i++)
		HEX1_SET((__gliss_1_i % 8), ((uint8_t)(_field32_generic(_HEX03, __gliss_1_i, __gliss_1_i, 1 ))));

}

/* HEX4 port functions */

static void on_input_HEX4(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX4_BASE);

}

static void on_update_HEX4(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_4_i;
	for(__gliss_4_i = 0; __gliss_4_i != 7+ 1; __gliss_4_i++)
		HEX4_SET((__gliss_4_i % 8), ((uint8_t)(_field32_generic(_HEX45, __gliss_4_i, __gliss_4_i, 1 ))));

}

/* HEX3 port functions */

static void on_input_HEX3(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX3_BASE);

}

static void on_update_HEX3(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_3_i;
	for(__gliss_3_i = 24; __gliss_3_i != 31+ 1; __gliss_3_i++)
		HEX3_SET((__gliss_3_i % 8), ((uint8_t)(_field32_generic(_HEX03, __gliss_3_i, __gliss_3_i, 1 ))));

}

/* HEX0 port functions */

static void on_input_HEX0(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX0_BASE);

}

static void on_update_HEX0(csim_inst_t *inst) {
	seven_seg_controller_inst_t *__inst = (seven_seg_controller_inst_t *)inst;
	uint32_t __gliss_0_i;
	for(__gliss_0_i = 0; __gliss_0_i != 7+ 1; __gliss_0_i++)
		HEX0_SET((__gliss_0_i % 8), ((uint8_t)(_field32_generic(_HEX03, __gliss_0_i, __gliss_0_i, 1 ))));

}




/**
 * seven_seg_controller description structure.
 */
csim_component_t  seven_seg_controller_component = {
    "seven_seg_controller",
    CSIM_SIMPLE,
    0,					// version
    regs,				// registers
    2,	// register count
    ports,				// ports
    6,		// port count
    sizeof(seven_seg_controller_inst_t),
    seven_seg_controller_construct,
    seven_seg_controller_destruct,
    seven_seg_controller_reset
};
