/* Generated by gliss-csim (124/03/03 16:49:30) copyright (c) 2024 IRIT - UPS */

#include <stdio.h>
#include <stdlib.h>
#include <csim.h>
#include "csim-rt.h"

#define ____COMP_NUM		(inst->number)

#	define input_BASE	0
#	define _input	__inst->input
#	define input_PORT	&ports[input_BASE]
#		define input_SET(i, x)	\
			{ \
				if(_input[i] != x) { \
					_input[i] = x; \
					csim_send_digital(inst, input_PORT + i, _input[i]); \
				} \
			}


/**
 * Instance definition.
 */
typedef struct  seven_seg_display_inst_t {
    csim_inst_t inst;

			uint8_t input[8];
;
}  seven_seg_display_inst_t;


/* pre-definitiion of update functions */
	static void on_update_input(csim_inst_t *inst);


static void on_update_all(csim_inst_t *inst) {
		on_update_input(inst);
	
}


/**
 * Reset the instance.
 * @param inst	Instance to reset.
 */
static void  seven_seg_display_reset(csim_inst_t *inst) {
    seven_seg_display_inst_t * seven_seg_display_inst = ( seven_seg_display_inst_t *)inst;
}

/**
 * Construct an instance.
 * @param inst	Instance to construct.
 */
static void seven_seg_display_construct(csim_inst_t *inst, csim_confs_t confs) {
    seven_seg_display_inst_t * seven_seg_display_inst = ( seven_seg_display_inst_t *)inst;
    seven_seg_display_reset(inst);
}

/**
 * Destruct the instance.
 * @param inst	Instance to destruct.
 */
static void seven_seg_display_destruct(csim_inst_t *inst) {
}





/**
 * Array of registers.
 */
static csim_reg_t regs[] = {

};


/* predeclaration of port-functions */
static void on_input_input(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);



/**
 * Array of ports.
 */
static csim_port_t ports[] = {
				{
					"input0",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input1",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input2",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input3",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input4",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input5",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input6",
					CSIM_ELECTRIC,
					on_input_input
				},
				{
					"input7",
					CSIM_ELECTRIC,
					on_input_input
				},


};


/* input port functions */

static void on_input_input(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_seg_display_inst_t *__inst = (seven_seg_display_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + input_BASE);

}

static void on_update_input(csim_inst_t *inst) {
	seven_seg_display_inst_t *__inst = (seven_seg_display_inst_t *)inst;

}


//hand coded

#define ZERO  0b00111111
#define ONE   0b00000011
#define TWO   0b01011011
#define THREE 0b01001111
#define FOUR  0b01100110
#define FIVE  0b01101101
#define SIX   0b01111101
#define SEVEN 0b00000111
#define EIGHT 0b01111111
#define NINE  0b01110111

static int seven_seg_display_display(char *buf, csim_iocomp_inst_t *inst) {
	seven_seg_display_inst_t *instance = (seven_seg_display_inst_t *)inst;
	char displays[] = "0 0 0 0 0 0";
	for (uint8_t i = 0; i < 6; i++)
	{
		uint8_t input = 0;
		for (uint8_t i = 0; i < 7; i++)
			input += (instance->input[i] << i);
		
		switch (input & 0b01111111) {
			case ZERO :
				displays[2*i] = '0';
				break;
			case ONE :
				displays[2*i] = '1';
				break;	
			case TWO :
				displays[2*i] = '2';
				break;
			case THREE :
				displays[2*i] = '3';
				break;
			case FOUR :
				displays[2*i] = '4';
				break;
			case FIVE :
				displays[2*i] = '5';
				break;
			case SIX :
				displays[2*i] = '6';
				break;
			case SEVEN :
				displays[2*i] = '7';
				break;
			case EIGHT :
				displays[2*i] = '8';
				break;
			case NINE :
				displays[2*i] = '9';
				break;
			default :
				displays[2*i] = 'X';
		}
	}

	return sprintf(buf,displays);
}


static void seven_seg_display_on_key(char key, csim_iocomp_inst_t *inst) {
}

csim_iocomp_t seven_seg_display_component = {
	{
		"seven_seg_display",
		CSIM_IO,
		0,
		regs,
		0,
		ports,
		1,
		sizeof(seven_seg_display_inst_t),
		seven_seg_display_construct,
		seven_seg_display_destruct,
		seven_seg_display_reset
	},
	seven_seg_display_display,
	seven_seg_display_on_key
};
