/* Generated by gliss-csim (124/03/03 16:49:30) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_SEVEN_SEG_DISPLAY_H
#define  STM32_SEVEN_SEG_DISPLAY_H

#include <csim.h>

extern csim_iocomp_t  seven_seg_display_component;

#endif /*  STM32_SEVEN_SEG_DISPLAY_H */
