/* Generated by gliss-csim (125/03/25 22:05:28) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_TC16BIT1_H
#define  ATMEGA328P_TC16BIT1_H

#include <csim.h>

extern csim_component_t  tc16bit1_component;

#endif /*  ATMEGA328P_TC16BIT1_H */
