/* Generated by gliss-csim (125/03/24 10:46:34) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_TC8BIT0_H
#define  ATMEGA328P_TC8BIT0_H

#include <csim.h>

extern csim_component_t  tc8bit0_component;

#endif /*  ATMEGA328P_TC8BIT0_H */
