/* Generated by gliss-csim (125/03/24 14:29:30) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_TC8BIT2_H
#define  ATMEGA328P_TC8BIT2_H

#include <csim.h>

extern csim_component_t  tc8bit2_component;

#endif /*  ATMEGA328P_TC8BIT2_H */
