/* Generated by gliss-csim (124/05/07 16:37:37) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_TIMER_H
#define  STM32_TIMER_H

#include <csim.h>

extern csim_component_t  timer_component;

#endif /*  STM32_TIMER_H */
