/* Generated by gliss-csim (124/05/01 22:20:40) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_LEDS10_H
#define  STM32_LEDS10_H

#include <csim.h>

extern csim_component_t  leds10_component;

#endif /*  STM32_LEDS10_H */
