/* Generated by gliss-csim (124/05/03 15:39:18) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_SEVEN_SEG_CONTROLLER_H
#define  STM32_SEVEN_SEG_CONTROLLER_H

#include <csim.h>

extern csim_component_t  seven_seg_controller_component;

#endif /*  STM32_SEVEN_SEG_CONTROLLER_H */
