/* Generated by gliss-csim (124/04/21 15:59:12) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_SEVEN_SEG_DISPLAY_H
#define  STM32_SEVEN_SEG_DISPLAY_H

#include <csim.h>

extern csim_component_t  seven_seg_display_component;

#endif /*  STM32_SEVEN_SEG_DISPLAY_H */
