/* Generated by gliss-csim (124/04/06 15:58:38) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_TIM_H
#define  STM32_TIM_H

#include <csim.h>

extern csim_component_t  TIM_component;

#endif /*  STM32_TIM_H */
