/* Generated by gliss-csim (124/04/06 15:58:38) copyright (c) 2024 IRIT - UPS */

#include <stdio.h>
#include <stdlib.h>
#include <csim.h>
#include "csim-rt.h"

#define ____COMP_NUM		(inst->number)
#	define _ARR	__inst->ARR
#	define _CNT	__inst->CNT
#	define _CR1	__inst->CR1
#	define _SR	__inst->SR
#	define _last	__inst->last
#	define _running	__inst->running



/**
 * Instance definition.
 */
typedef struct  TIM_inst_t {
    csim_inst_t inst;
			uint16_t ARR;
			uint16_t CNT;
			uint32_t CR1;
			uint32_t SR;
			uint32_t last;
			uint8_t running;

;
}  TIM_inst_t;


/* pre-definitiion of update functions */


static void on_update_all(csim_inst_t *inst) {
	
}


/**
 * Reset the instance.
 * @param inst	Instance to reset.
 */
static void  TIM_reset(csim_inst_t *inst) {
    TIM_inst_t * TIM_inst = ( TIM_inst_t *)inst;
}

/**
 * Construct an instance.
 * @param inst	Instance to construct.
 */
static void TIM_construct(csim_inst_t *inst, csim_confs_t confs) {
    TIM_inst_t * TIM_inst = ( TIM_inst_t *)inst;
    TIM_reset(inst);
}

/**
 * Destruct the instance.
 * @param inst	Instance to destruct.
 */
static void TIM_destruct(csim_inst_t *inst) {
}


/* ARR register functions */

static void name_ARR(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_ARR", inst->number);
}

static void display_ARR(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->ARR);;
}

static csim_word_t read_ARR(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->ARR;
}
 
static csim_word_t get_ARR(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->ARR;
}
 
static void set_ARR(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->ARR != val) {
			__inst->ARR = val;
			on_update_all(inst);
		}
	
}

static void write_ARR(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_ARR(inst, num, val);
	
}

/* CNT register functions */

static void name_CNT(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_CNT", inst->number);
}

static void display_CNT(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->CNT);;
}

static csim_word_t read_CNT(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->CNT;
}
 
static csim_word_t get_CNT(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->CNT;
}
 
static void set_CNT(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->CNT != val) {
			__inst->CNT = val;
			on_update_all(inst);
		}
	
}

static void write_CNT(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_CNT(inst, num, val);
	
}

/* CR1 register functions */

static void name_CR1(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_CR1", inst->number);
}

static void display_CR1(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->CR1);;
}

static csim_word_t read_CR1(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->CR1;
}
 
static csim_word_t get_CR1(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->CR1;
}
 
static void set_CR1(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->CR1 != val) {
			__inst->CR1 = val;
			on_update_all(inst);
		}
	
}

static void write_CR1(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_CR1(inst, num, val);
	
}

/* SR register functions */

static void name_SR(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_SR", inst->number);
}

static void display_SR(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->SR);;
}

static csim_word_t read_SR(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->SR;
}
 
static csim_word_t get_SR(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->SR;
}
 
static void set_SR(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->SR != val) {
			__inst->SR = val;
			on_update_all(inst);
		}
	
}

static void write_SR(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_SR(inst, num, val);
	
}

/* last register functions */

static void name_last(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_last", inst->number);
}

static void display_last(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->last);;
}

static csim_word_t read_last(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->last;
}
 
static csim_word_t get_last(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->last;
}
 
static void set_last(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->last != val) {
			__inst->last = val;
			on_update_all(inst);
		}
	
}

static void write_last(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_last(inst, num, val);
	
}

/* running register functions */

static void name_running(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "TIM%d_running", inst->number);
}

static void display_running(csim_inst_t *inst, int num, char *__buffer, int size) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->running);;
}

static csim_word_t read_running(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
				return __inst->running;
}
 
static csim_word_t get_running(csim_inst_t *inst, int num) {
		TIM_inst_t *__inst = (TIM_inst_t *)inst;
			return __inst->running;
}
 
static void set_running(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		if(__inst->running != val) {
			__inst->running = val;
			on_update_all(inst);
		}
	
}

static void write_running(csim_inst_t *inst, int num, csim_word_t val) {
	TIM_inst_t *__inst = (TIM_inst_t *)inst;
		set_running(inst, num, val);
	
}




/**
 * Array of registers.
 */
static csim_reg_t regs[] = {
	{
		"ARR",		// name
		0x2c,		// offset
		2,		// size
		1,		// count
		2,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_ARR,
		display_ARR,
		read_ARR,
		write_ARR,
		get_ARR,
		set_ARR
	},
	{
		"CNT",		// name
		0x24,		// offset
		2,		// size
		1,		// count
		2,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_CNT,
		display_CNT,
		read_CNT,
		write_CNT,
		get_CNT,
		set_CNT
	},
	{
		"CR1",		// name
		0x0,		// offset
		4,		// size
		1,		// count
		4,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_CR1,
		display_CR1,
		read_CR1,
		write_CR1,
		get_CR1,
		set_CR1
	},
	{
		"SR",		// name
		0x10,		// offset
		4,		// size
		1,		// count
		4,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_SR,
		display_SR,
		read_SR,
		write_SR,
		get_SR,
		set_SR
	},
	{
		"last",		// name
		0x100,		// offset
		4,		// size
		1,		// count
		4,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_last,
		display_last,
		read_last,
		write_last,
		get_last,
		set_last
	},
	{
		"running",		// name
		0x200,		// offset
		0,		// size
		1,		// count
		0,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_running,
		display_running,
		read_running,
		write_running,
		get_running,
		set_running
	},

};


/* predeclaration of port-functions */



/**
 * Array of ports.
 */
static csim_port_t ports[] = {

};





/**
 * TIM description structure.
 */
csim_component_t  TIM_component = {
    "TIM",
    CSIM_SIMPLE,
    0,					// version
    regs,				// registers
    6 ,	// register count
    ports,				// ports
    0,		// port count
    sizeof(TIM_inst_t),
    TIM_construct,
    TIM_destruct,
    TIM_reset
};
