/* Generated by gliss-csim (124/05/03 18:46:08) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_TIM_H
#define  STM32_TIM_H

#include <csim.h>

extern csim_component_t  TIM_component;

#endif /*  STM32_TIM_H */
