/* Generated by gliss-csim (124/03/02 14:46:33) copyright (c) 2024 IRIT - UPS */

#include <stdio.h>
#include <stdlib.h>
#include <csim.h>
#include "csim-rt.h"

#define ____COMP_NUM		(inst->number)
#	define _HEX	__inst->HEX

#	define HEX03_BASE	0
#	define _HEX03	__inst->HEX03
#	define HEX03_PORT	&ports[HEX03_BASE]
#		define HEX03_SET(i, x)	\
			{ \
				if(_HEX03[i] != x) { \
					_HEX03[i] = x; \
					csim_send_digital(inst, HEX03_PORT + i, _HEX03[i]); \
				} \
			}
#	define HEX45_BASE	32
#	define _HEX45	__inst->HEX45
#	define HEX45_PORT	&ports[HEX45_BASE]
#		define HEX45_SET(i, x)	\
			{ \
				if(_HEX45[i] != x) { \
					_HEX45[i] = x; \
					csim_send_digital(inst, HEX45_PORT + i, _HEX45[i]); \
				} \
			}


/**
 * Instance definition.
 */
typedef struct  seven_segment_inst_t {
    csim_inst_t inst;
			uint8_t HEX[8];

			uint8_t HEX03[32];
			uint8_t HEX45[32];
;
}  seven_segment_inst_t;


/* pre-definitiion of update functions */
	static void on_update_HEX03(csim_inst_t *inst);
	static void on_update_HEX45(csim_inst_t *inst);


static void on_update_all(csim_inst_t *inst) {
		on_update_HEX03(inst);
		on_update_HEX45(inst);
	
}


/**
 * Reset the instance.
 * @param inst	Instance to reset.
 */
static void  seven_segment_reset(csim_inst_t *inst) {
    seven_segment_inst_t * seven_segment_inst = ( seven_segment_inst_t *)inst;
}

/**
 * Construct an instance.
 * @param inst	Instance to construct.
 */
static void seven_segment_construct(csim_inst_t *inst, csim_confs_t confs) {
    seven_segment_inst_t * seven_segment_inst = ( seven_segment_inst_t *)inst;
    seven_segment_reset(inst);
}

/**
 * Destruct the instance.
 * @param inst	Instance to destruct.
 */
static void seven_segment_destruct(csim_inst_t *inst) {
}


/* HEX register functions */

static void name_HEX(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
	snprintf(__buffer, size, "seven_segment%d_HEX", inst->number);
}

static void display_HEX(csim_inst_t *inst, int num, char *__buffer, int size) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
	snprintf(__buffer, size, "%d", __inst->HEX);;
}

static csim_word_t read_HEX(csim_inst_t *inst, int num) {
		seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
				return __inst->HEX[num];
}
 
static csim_word_t get_HEX(csim_inst_t *inst, int num) {
		seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
			return __inst->HEX[num];
}
 
static void set_HEX(csim_inst_t *inst, int num, csim_word_t val) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
		if(__inst->HEX[num] != val) {
			__inst->HEX[num] = val;
			on_update_all(inst);
		}
	
}

static void write_HEX(csim_inst_t *inst, int num, csim_word_t val) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;
		set_HEX(inst, num, val);
	
}




/**
 * Array of registers.
 */
static csim_reg_t regs[] = {
	{
		"HEX",		// name
		0x0,		// offset
		8,		// size
		6,		// count
		1,		// stride
		0,				// flags
		CSIM_INT,		// signal type
		name_HEX,
		display_HEX,
		read_HEX,
		write_HEX,
		get_HEX,
		set_HEX
	},

};


/* predeclaration of port-functions */
static void on_input_HEX03(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);
static void on_input_HEX45(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val);



/**
 * Array of ports.
 */
static csim_port_t ports[] = {
				{
					"HEX030",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX031",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX032",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX033",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX034",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX035",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX036",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX037",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX038",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX039",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0310",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0311",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0312",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0313",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0314",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0315",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0316",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0317",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0318",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0319",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0320",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0321",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0322",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0323",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0324",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0325",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0326",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0327",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0328",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0329",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0330",
					CSIM_ELECTRIC,
					on_input_HEX03
				},
				{
					"HEX0331",
					CSIM_ELECTRIC,
					on_input_HEX03
				},

				{
					"HEX450",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX451",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX452",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX453",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX454",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX455",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX456",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX457",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX458",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX459",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4510",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4511",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4512",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4513",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4514",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4515",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4516",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4517",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4518",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4519",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4520",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4521",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4522",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4523",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4524",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4525",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4526",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4527",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4528",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4529",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4530",
					CSIM_ELECTRIC,
					on_input_HEX45
				},
				{
					"HEX4531",
					CSIM_ELECTRIC,
					on_input_HEX45
				},


};


/* HEX03 port functions */

static void on_input_HEX03(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX03_BASE);
	_HEX[____INDEX] = ((uint8_t)(_HEX03[____INDEX]));

}

static void on_update_HEX03(csim_inst_t *inst) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;

}

/* HEX45 port functions */

static void on_input_HEX45(csim_port_inst_t *inst, csim_value_type_t type, csim_value_t val) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst->inst;
	int ____INDEX = inst->port - (ports + HEX45_BASE);
	if((____INDEX <= (32 * 6)))
		_HEX[(____INDEX + 32)] = ((uint8_t)(_HEX45[____INDEX]));

}

static void on_update_HEX45(csim_inst_t *inst) {
	seven_segment_inst_t *__inst = (seven_segment_inst_t *)inst;

}




/**
 * seven_segment description structure.
 */
csim_component_t  seven_segment_component = {
    "seven_segment",
    CSIM_SIMPLE,
    0,					// version
    regs,				// registers
    1,	// register count
    ports,				// ports
    2,		// port count
    sizeof(seven_segment_inst_t),
    seven_segment_construct,
    seven_segment_destruct,
    seven_segment_reset
};
