/* Generated by gliss-csim (124/03/02 14:46:33) copyright (c) 2024 IRIT - UPS */

#ifndef  STM32_SEVEN_SEGMENT_H
#define  STM32_SEVEN_SEGMENT_H

#include <csim.h>

extern csim_component_t  seven_segment_component;

#endif /*  STM32_SEVEN_SEGMENT_H */
