/* Generated by gliss-csim (125/03/24 12:37:42) copyright (c) 2024 IRIT - UPS */

#ifndef  ATMEGA328P_PORTC2_H
#define  ATMEGA328P_PORTC2_H

#include <csim.h>

extern csim_component_t  portc2_component;

#endif /*  ATMEGA328P_PORTC2_H */
